### ISSUE TITLE
Campos obligatorios que faltan

### ISSUE THREAD

**Issue by Lainezz** [ImZiki/Dota2API-REST#1]
Recuerda que en el README deben aparecer los siguientes campos:
a.
Nombre del proyecto
b.
Idea del proyecto
c.
Justificación del proyecto
d.
Descripción detallada de las tablas que intervendrán en el proyecto

Mucho ánimo y gran trabajo Dani!! Siempre es un gusto trabajar con alumnos que se involucran y lo dan todo de sí.

**Comment by ImZiki** [comment]
Diego, he reestructurado un poco dandole otro enfoque a la presentación del readme y una descripcion algo mas detallada y ordenada de las tablas y sus atributos.  Espero que asi se entienda algo mejor el proyecto y si cumple con los requisitos.
